# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEE8jjv2j8OROCNkDuqneA3nKiiNyLoO
"""

import streamlit as st
import string
import secrets
import pyperclip

# ----------------------
# Password Generator Logic
# ----------------------
def generate_password(length, use_upper, use_lower, use_digits, use_symbols):
    characters = ''
    if use_upper:
        characters += string.ascii_uppercase
    if use_lower:
        characters += string.ascii_lowercase
    if use_digits:
        characters += string.digits
    if use_symbols:
        characters += string.punctuation

    if not characters:
        return "⚠️ Please select at least one character type!"

    password = ''.join(secrets.choice(characters) for _ in range(length))
    return password

# ----------------------
# Streamlit UI
# ----------------------
st.set_page_config(page_title="🔐 Password Generator", layout="centered")
st.title("🔐 Secure Password Generator")

# Input controls
length = st.slider("Password Length", min_value=4, max_value=50, value=12)
use_upper = st.checkbox("Include Uppercase Letters (A-Z)", value=True)
use_lower = st.checkbox("Include Lowercase Letters (a-z)", value=True)
use_digits = st.checkbox("Include Numbers (0-9)", value=True)
use_symbols = st.checkbox("Include Symbols (!@#$)", value=True)

# Generate button
if st.button("Generate Password"):
    pwd = generate_password(length, use_upper, use_lower, use_digits, use_symbols)
    st.text_input("🔑 Your Password:", value=pwd, key="password_output")
    if pwd and "⚠️" not in pwd:
        pyperclip.copy(pwd)
        st.success("✅ Password copied to clipboard!")