# -*- coding: utf-8 -*-
"""password_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c6jL1qvelMBTSM8eCwO1Rmv1yWMWmCOM
"""

import string
import secrets

def generate_password(length=12, use_upper=True, use_lower=True, use_digits=True, use_symbols=True):
    characters = ''
    if use_upper:
        characters += string.ascii_uppercase
    if use_lower:
        characters += string.ascii_lowercase
    if use_digits:
        characters += string.digits
    if use_symbols:
        characters += string.punctuation

    if not characters:
        return "⚠️ Please select at least one character type!"

    password = ''.join(secrets.choice(characters) for _ in range(length))
    return password

# Sample test
generate_password(length=16, use_upper=True, use_lower=True, use_digits=True, use_symbols=True)